backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/img" 
public_folder: "/assets/img"
collections:
  - name: "reviews"
    label: "Reviews"
    folder: "src/reviews"
    create: true
    slug: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: "Movie Title", name: "title", widget: "string" }
      - { label: "Movie Year", name: "year", widget: "datetime" }
      - { label: "Review Author", name: "author", widget: "string" }
      - { label: "Rating", name: "rating", widget: "select", options: ["1","2","3","4","5","6","7","8","9,"10"] }
      - { label: "Description/Synopsis", name: "description", widget: "string" }
      - { label: "Director", name: "director", widget: "string" }
      - { label: "Writer(s)", name: "writer", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }