backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/img" 
public_folder: "/assets/img"
collections:
  - name: "reviews"
    label: "Reviews"
    folder: "src/reviews"
    create: true
    slug: "{{slug}}"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    fields:
      - { label: "Movie Title", name: "title", widget: "string" }
      - { label: "Movie Year", name: "year", widget: "number"}
      - { label: "Genre(s) (Separated by comma)", name: "genre", widget: "list" }
      - { label: "Review Author", name: "author", widget: "string" }
      - { label: "Rating", name: "rating", widget: "select", options: ["1","1.5","2","2.5","3","3.5","4","4.5","5"] }
      - { label: "Description/Synopsis", name: "description", widget: "string" }
      - { label: "Director", name: "director", widget: "string" }
      - { label: "Writer(s) (Separated by comma)", name: "writer", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "image-alt", widget: "string", default: "MOVIE NAME movie poster"}
      - { label: "Body", name: "body", widget: "markdown" }